# Copyright 2020 Redpanda Data, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: build-test
on: [push, pull_request]

jobs:
  build:
    name: build redpanda
    runs-on: ubuntu-20.04

    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: prepare toolchain container
          run: |
            docker pull docker.io/vectorized/redpanda-toolchain || true
            chmod 0775 install-dependencies.sh
            cp tools/docker/Dockerfile.ignore .dockerignore
            docker build \
              --cache-from docker.io/vectorized/redpanda-toolchain \
              --tag rp-toolchain \
              --file tools/docker/Dockerfile \
              .
            rm .dockerignore

        - name: retrieve ccache cache files
          uses: actions/cache/restore@v3
          with:
            path: /dev/shm/redpanda
            key: ccache-${{github.ref}}-${{github.sha}}
            restore-keys: ccache-${{github.ref}} ccache

        - name: set fx.aio-max-nr
          run: sudo sysctl -w fs.aio-max-nr=10485760

        - name: build & test
          run: |
            docker run --rm \
              -e CCACHE_COMPRESS=true \
              -e CCACHE_COMPRESSLEVEL=6 \
              -e CCACHE_MAXSIZE=200M \
              --privileged \
              --ipc=host \
              -v $PWD:$PWD \
              -w $PWD \
              rp-toolchain \
              ./build.sh

        - name: save ccache cache files
          uses: actions/cache/save@v3
          if: success() || failure()
          with:
            path: /dev/shm/redpanda
            key: ccache-${{github.ref}}-${{github.sha}}
